###################### Running Tests ######################


###################### Getting Shard IDs ######################

F
###################### Getting the Members of Shard IDs ######################

E
###################### Getting the Shard ID of the nodes ######################

E
###################### Putting keys/values to the store ######################

E
###################### Getting keys/values from the store ######################

E
###################### Getting key count of each shard ######################

EE
###################### Doing Impossible Resharding ######################

F
###################### Doing Resharding ######################

F
======================================================================
ERROR: test_b_shard_id_members (__main__.TestHW3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_assignment4_v3.py", line 137, in test_b_shard_id_members
    shard1 = self.shardIdList[0]
IndexError: list index out of range

======================================================================
ERROR: test_c_node_shard_id (__main__.TestHW3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_assignment4_v3.py", line 164, in test_c_node_shard_id
    shard1 = self.shardIdList[0]
IndexError: list index out of range

======================================================================
ERROR: test_d_put_key_value_operation (__main__.TestHW3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_assignment4_v3.py", line 221, in test_d_put_key_value_operation
    responseInJson = response.json()
  File "C:\Users\kenco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\kenco\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\kenco\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\kenco\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)

======================================================================
ERROR: test_e_get_key_value_operation (__main__.TestHW3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_assignment4_v3.py", line 242, in test_e_get_key_value_operation
    responseInJson = response.json()
  File "C:\Users\kenco\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\kenco\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\kenco\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\kenco\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)

======================================================================
ERROR: test_f_shard_key_count (__main__.TestHW3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_assignment4_v3.py", line 251, in test_f_shard_key_count
    shard1 = self.shardIdList[0]
IndexError: list index out of range

======================================================================
ERROR: test_g_add_new_node (__main__.TestHW3)
----------------------------------------------------------------------
Traceback (most recent call last):
    shard2 = self.shardIdList[1]
IndexError: list index out of range

======================================================================
FAIL: test_a_get_shard_ids (__main__.TestHW3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_assignment4_v3.py", line 115, in test_a_get_shard_ids
    self.assertEqual(len(shardIdsFromNode1.split(",")), shardCount)
AssertionError: 1 != 2

======================================================================
FAIL: test_h_impossible_reshard (__main__.TestHW3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_assignment4_v3.py", line 338, in test_h_impossible_reshard
    self.assertEqual(response.status_code, 400)
AssertionError: 404 != 400

======================================================================
FAIL: test_i_possible_reshard (__main__.TestHW3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".\test_assignment4_v3.py", line 345, in test_i_possible_reshard
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

----------------------------------------------------------------------
Ran 9 tests in 20.122s

FAILED (failures=3, errors=6)